name = "obsidian-cf-sync"
main = "src/index.ts"
compatibility_date = "2026-09-09"

[[durable_objects.bindings]]
name = "ACCOUNT"
class_name = "AccountDO"

[[durable_objects.bindings]]
name = "VAULTS"
class_name = "VaultDO"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["AccountDO", "VaultDO"]

[[r2_buckets]]
binding = "BUCKET"
bucket_name = "obsidian-cf-sync"

[observability]
redact_query_string = true

[observability.logs]
enabled = true
head_sampling_rate = 1
invocation_logs = true
